config/routes.rb
RubynepalWebsiteApp::Application.routes.draw do

  resources :members do

    member do
      put :toggle_status
    end
    collection do
      get :all
      put :refresh_data
    end

  end

  root :to => 'members#new'

end

app/models/member.rb
require_relative '../../lib/github'

class Member < ActiveRecord::Base
  attr_accessible :email, :employement, :full_name, :github, :linkedin, :short_bio, :twitter, :score, :avatar_url
  validates_presence_of :email, :full_name, :github

  default_scope order('created_at DESC')

  def populate_score_and_avatar
    gh_hash = GithubScorer.new(Github::Event.new(self.github).get, self.github)
    self.score = gh_hash.total_score
    self.avatar_url = "http://gravatar.com/avatar/#{gh_hash.avatar}"
    self.save!
  end

  def self.refresh_data
    members = Member.where(active: true).all
    members.each do |e|
      gh = GithubScorer.new(Github::Event.new(e.github).get, e.github)
      e.update_attribute(:score, gh.total_score)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == APP_CONFIG[:http_username]  && password == APP_CONFIG[:http_password]
    end
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  skip_before_filter :authenticate, only: [:new, :create, :all]

  def all
    render json: Member.where(active: true).all, :except => [:active, :updated_at]
  end

  # GET /members
  # GET /members.json
  def index
    @members = Member.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @members }
    end
  end

  # GET /members/1
  # GET /members/1.json
  def show
    @member = Member.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/new
  # GET /members/new.json
  def new
    @member = Member.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/1/edit
  def edit
    @member = Member.find(params[:id])
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(params[:member])

    respond_to do |format|
      if @member.save
        format.html { render :partial => "/members/registration_success" }
        format.json { render json: @member, status: :created, location: @member }
      else
        format.html { render action: "new" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /members/1
  # PUT /members/1.json
  def update
    @member = Member.find(params[:id])

    respond_to do |format|
      if @member.update_attributes(params[:member])
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member = Member.find(params[:id])
    @member.destroy

    respond_to do |format|
      format.html { redirect_to members_url }
      format.json { head :no_content }
    end
  end

  def toggle_status
    @member = Member.find(params[:id])
    @member.update_attribute(:active, !@member.active)
    @member.populate_score_and_avatar if @member.active
    redirect_to members_path, notice: 'Member was successfully updated.'
  end

  def refresh_data
    Member.refresh_data
    redirect_to members_path, notice: "All member's data refreshed."
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RubynepalWebsiteApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "full name *" %><br />
    <%= f.text_field :full_name, required: "required" %>
  </div>
  <div class="email">
    <%= f.label "email *" %><br />
    <%= f.email_field :email, required: "required" %>
  </div>
  <div class="field">
    <%= f.label "twitter username" %><br />
    <%= f.text_field :twitter %>
  </div>
  <div class="field">
    <%= f.label "github username *" %><br />
    <%= f.text_field :github, required: "required" %>
  </div>
  <div class="field">
    <%= f.label "linkedin url" %><br />
    <%= f.text_field :linkedin %>
  </div>
  <div class="field">
    <%= f.label :employement %><br />
    <%= f.text_field :employement %>
  </div>
  <div class="field">
    <%= f.label "Short Bio" %><br />
    <%= f.text_area :short_bio, rows: 10, cols: 50 %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", class: "btn"%>
  </div>
<% end %>

app/views/members/_registration_success.html.erb
<style type="text/css">
  body{ margin: 0}
  .note{
    font-family: helvetica, sans-serif,verdana, arial;
    color: rgb(59, 175, 82);
    font-weight: bold;
    font-size: 22px;
  }
</style>
<div class="note">
  We have received your details. We will get back to you asap.
</div>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<h1>Listing All Members</h1>
<div class="pull-right">
    <%= link_to "Refresh Data", refresh_data_members_path, method: :put, title: "refresh all member's and get recomputes score form github"%>
</div>
<table class="gridtable">
  <tr>
    <th>Full name</th>
    <th>Email</th>
    <th>Twitter</th>
    <th>Github</th>
    <th>Linkedin</th>
    <th>Short bio</th>
    <th>Employement</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @members.each do |member| %>
  <tr>
    <td>
        <%=link_to "#{member.id}.#{member.full_name}", member %>
        <br />
        <%=time_ago_in_words(member.created_at)%> ago
    </td>
    <td><%= member.email %></td>
    <td><%= member.twitter %></td>
    <td><%= member.github %></td>
    <td><%= member.linkedin %></td>
    <td><%= truncate(member.short_bio, :length => 50) %></td>
    <td><%= member.employement %></td>
    <td><%=member.active ? "active" : "inactive" %></td>
    <td><%= link_to "#{ member.active ? 'Disable' : 'Enable'}", toggle_status_member_path(member), method: :put %></td>
    <td><%= link_to 'Edit', edit_member_path(member) %></td>
    <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New Member Application Form</h1>

<%= render 'form' %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Full name:</b>
  <%= @member.full_name %>
</p>

<p>
  <b>Email:</b>
  <%= @member.email %>
</p>

<p>
  <b>Twitter:</b>
  <%= @member.twitter %>
</p>

<p>
  <b>Github:</b>
  <%= @member.github %>
</p>

<p>
  <b>Linkedin:</b>
  <%= @member.linkedin %>
</p>

<p>
  <b>Short bio:</b>
  <%= @member.short_bio %>
</p>

<p>
  <b>Employement:</b>
  <%= @member.employement %>
</p>


<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>